version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vockagolordy/kittygram_backend
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/static
      - media:/media
  frontend:
    image: vockagolordy/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vockagolordy/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
